//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyLogTb
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfDay { get; set; }
        public string Satement { get; set; }
        public Nullable<int> Dayofweekid { get; set; }
    
        public virtual DayofWeak DayofWeak { get; set; }
    }
}
